services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-logs:/var/log/nginx
      - ./nginx/security-headers.conf:/etc/nginx/security-headers.conf
    depends_on:
      - php
      - db
    networks:
      - wordpress-network

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./wordpress:/var/www/html
      - ./php-errors:/var/log
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=wordpress_password
      - WORDPRESS_DB_NAME=wordpress_db
    networks:
      - wordpress-network

  db:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 'wordpress_password'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wordpress_user
      PMA_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - wordpress-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - "9443:9443"
      - "8000:8000"
    networks:
      - wordpress-network

networks:
   wordpress-network:
    driver: bridge
